kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 150Gi
  storageClassName: nextcloud-data